# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"\'\n\x06Tensor\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x03\"(\n\x0cModelWeights\x12\x18\n\x07tensors\x18\x01 \x03(\x0b\x32\x07.Tensor\"\x12\n\x03\x41\x63k\x12\x0b\n\x03msg\x18\x01 \x01(\t23\n\rModelExchange\x12\"\n\x0bSendWeights\x12\r.ModelWeights\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=15
  _globals['_TENSOR']._serialized_end=54
  _globals['_MODELWEIGHTS']._serialized_start=56
  _globals['_MODELWEIGHTS']._serialized_end=96
  _globals['_ACK']._serialized_start=98
  _globals['_ACK']._serialized_end=116
  _globals['_MODELEXCHANGE']._serialized_start=118
  _globals['_MODELEXCHANGE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
